"""FireWatch public package exports."""

from client import FireWatchClient
from models import FireWatchAction, FireWatchObservation

# Alias that matches the autogenerated OpenEnv quick-start snippet more closely.
FireWatchEnv = FireWatchClient

__all__ = [
    "FireWatchAction",
    "FireWatchObservation",
    "FireWatchClient",
    "FireWatchEnv",
]
